### Python Exercise 1

In [16]:
fruits = ['Apple','Banana','Pineapple','Guava','Grapes']

In [17]:
fruits[:3]

['Apple', 'Banana', 'Pineapple']

In [18]:
fruits.append('Papaya')

In [19]:
fruits

['Apple', 'Banana', 'Pineapple', 'Guava', 'Grapes', 'Papaya']

In [20]:
for x in fruits:
    print(x)

Apple
Banana
Pineapple
Guava
Grapes
Papaya


In [31]:
fruit_dislike = 'Papaya'
for x in fruits:
    if x==fruit_dislike:
        print(x)

Papaya


In [1]:
courses = {
    "Data Analytics":"8",
    "SQL and Data Analsis":"8",
    "Business Intelligence Tools":"10",
    "Project Management":"9"
}

In [2]:
courses.update({"Big Data Analytics":"10"})

In [4]:
for x in courses.keys():
    print(x)

Data Analytics
SQL and Data Analsis
Business Intelligence Tools
Project Management
Big Data Analytics


In [6]:
for x in courses.values():
    print(x)

8
8
10
9
10


In [7]:
courses

{'Data Analytics': '8',
 'SQL and Data Analsis': '8',
 'Business Intelligence Tools': '10',
 'Project Management': '9',
 'Big Data Analytics': '10'}

In [8]:
for x,y in courses.items():
    print(x,y)

Data Analytics 8
SQL and Data Analsis 8
Business Intelligence Tools 10
Project Management 9
Big Data Analytics 10


In [1]:
import numpy as np

In [3]:
sales = np.arange(20)

In [12]:
sales

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [5]:
sales = sales*2

In [6]:
sales

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [7]:
np.mean(sales)

19.0

In [8]:
sales>np.mean(sales)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [9]:
import seaborn as sns

In [10]:
titanic = sns.load_dataset('titanic')

In [11]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [22]:
avg = np.mean(sales)
for x in sales:
    if x>np.mean(sales):
        print(x,"is greater than mean")
    elif x<avg:
        print(x,"is smaller than mean")


0 is smaller than mean
2 is smaller than mean
4 is smaller than mean
6 is smaller than mean
8 is smaller than mean
10 is smaller than mean
12 is smaller than mean
14 is smaller than mean
16 is smaller than mean
18 is smaller than mean
20 is greater than mean
22 is greater than mean
24 is greater than mean
26 is greater than mean
28 is greater than mean
30 is greater than mean
32 is greater than mean
34 is greater than mean
36 is greater than mean
38 is greater than mean


In [24]:
tips = sns.load_dataset('tips')

In [26]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [30]:
titanic.loc[:3,['alone','sex','alive']]

alone     sex alive
0  False    male    no
1  False  female   yes
2   True  female   yes
3  False  female   yes

In [39]:
titanic.loc[:,:'class']

survived  pclass     sex   age  sibsp  parch     fare embarked   class
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

[891 rows x 9 columns]

In [41]:
titanic.iloc[:10,[2,5,6]]

sex  parch     fare
0    male      0   7.2500
1  female      0  71.2833
2  female      0   7.9250
3  female      0  53.1000
4    male      0   8.0500
5    male      0   8.4583
6    male      0  51.8625
7    male      1  21.0750
8  female      2  11.1333
9  female      0  30.0708

In [49]:
titanic.loc[(titanic['alone']==False)].head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
3         1       1  female  35.0      1      0  53.1000        S  First   
7         0       3    male   2.0      3      1  21.0750        S  Third   
8         1       3  female  27.0      0      2  11.1333        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
3  woman       False    C  Southampton   yes  False  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False

In [50]:
titanic.head(2)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False

In [54]:
titanic.loc[(titanic['alone']==True)&(titanic['alive']=='no')].head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
4          0       3    male  35.0      0      0   8.0500        S  Third   
5          0       3    male   NaN      0      0   8.4583        Q  Third   
6          0       1    male  54.0      0      0  51.8625        S  First   
12         0       3    male  20.0      0      0   8.0500        S  Third   
14         0       3  female  14.0      0      0   7.8542        S  Third   

      who  adult_male deck  embark_town alive  alone  
4     man        True  NaN  Southampton    no   True  
5     man        True  NaN   Queenstown    no   True  
6     man        True    E  Southampton    no   True  
12    man        True  NaN  Southampton    no   True  
14  child       False  NaN  Southampton    no   True

In [59]:
#Only return the column fare for female passengers who were In 1st class of the ship
titanic.loc[(titanic['sex']=='female')&(titanic['class']=='First'),'fare'].head()

1      71.2833
3      53.1000
11     26.5500
31    146.5208
52     76.7292
Name: fare, dtype: float64